apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
  labels:
    type: multi
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
  initContainers:
    - name: ubuntu-init-container
      image: ubuntu
      command: ["sleep"]
      args: ["100"]
          

