apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: front-end
    region: prod
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
      env:
        - name: color
          value: blue
        - name: decouple
          value: false
          
