apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-1
  labels:
    app: front-end
    region: prod
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
      envFrom:
        - secretRef:
            name: app-secret          
