apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
  tolerations:
  - key: "example-key"
    value: "example-value"
    operator: "Equals"
    effect: "NoSchedule"
