apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-2
  labels:
    app: front-end
    region: prod
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
      env:
        - name: region
          valueFrom:
            configMapKeyRef:
              name: my-config-map
              key: region     

          
