apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-with-cm
  name: nginx-with-cm
spec:
  containers:
  - image: nginx
    name: nginx-with-cm
    envFrom:
      - configMapRef:
          name: my-config-map
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
